backend/routers/routes.js
public/src/scripts/classes/Player.js

- Criar novos métodos na class que possam redirecionar informações para as rotas do backend.
- Os métodos apenas se relacionarão aos paths, mas ainda poderão ser alterados posteriormente para ficarem alinhados às funções de mover-se e ao mapa do jogo.

create: new methods to class Player

---

backend/controllers/connection.js
backend/controllers/login.js
backend/controllers/logout.js
backend/controllers/walk.js
backend/database/index.js
backend/routers/routes.js

Criar o reset do winner e dos movimentos com um timeout
Criar uma rota para também fazer o reset do winner e movimentos
Não utilizei redis, apesar de criar os arquivos.
Realize o login
```
{
"name" :"Lay",
"path" : "login",
"channel": "general"
}
```
Depois mande movimentos
```
{
"name" :"Lay",
"path" : "walk",
"channel": "general",
"move": [[0,0], [0,1], [0,2]],
"id": "aqui coloque o id que retornou no login"
}
```
Depois finalize o jogo
```
{
"name" :"Lay",
"path" : "end",
"channel": "general",
"id": "aqui coloque o id que retornou no login"
}
```
Tente realizar outra requisição de end ou walk antes e depois de 30 segundos.

feat: create control reset winner and game

---

public/index.html
public/src/scripts/classes/Player.js
public/src/scripts/enter.js
public/src/scripts/html-content/enter-form.js

- Corrigir a ordem em que as funções são executadas para permitir que o usuário possa entrar e sair sucessivamente e repetidamente sem erros ou recarregamentos de página.
1 'buildar' os arquivos atualizados desta branch
2 executar a aplicação
3 entrar com um nome de usuário válido
4 clicar em sair
5 repetir os passos 3 e 4

fix: enter.js actions' order

---

public/index.html
public/index.js
public/src/scripts/enter.js
public/src/scripts/html-content/index.js
public/src/scripts/html-content/maze.js
public/src/scripts/runMazeIsa.js
public/src/styles/style.css

- Adicionar a tela de entrada antes do labirinto ser carregado.
- Ao entrar, um novo Player é criado e adicionado à lista de jogadores mockados. Dados para serem usados após a entrada podem ser capturados desse caminho.
1 'buildar' a aplicação
2 Executar o comando `npm run dev`
3 Inserir um nome de jogador válido e entrar
4 Validar a renderização do labirinto e do botão `Sair`
https://user-images.githubusercontent.com/95234159/166313412-cea76b7b-c475-41fb-b413-e14ca5a44840.mp4

create: enter page before maze

---

public/src/scripts/classes/MazeRenderizer.js

Remover o event listener quando o jogador ganhar a partida

feature: adcionado removeEventListener quando o jogador ganha a partida

---

public/index.js
public/src/scripts/enter.js
public/src/scripts/index.js

- Otimizar o script de entrada do jogador e adicionar exports para facilitar o uso das variiáveis.
- Este PR serve como uma resposta atrasada aos comentários do PR #17 
1 'buildar' a aplicação
2 Executar o comando `npm run dev`
3 Inserir um nome de jogador válido e entrar
4 Validar a renderização do labirinto e do botão `Sair`
https://user-images.githubusercontent.com/95234159/166313412-cea76b7b-c475-41fb-b413-e14ca5a44840.mp4

improve: export and use of enter.js variables

---

backend/routers/index.js
public/src/scripts/classes/Player.js
public/src/scripts/enter.js

Corrigir o login do jogador
Estou tentando tirar o import do mock e fazendo uma requisição ao servidor ao invés disso

Fix: Tirando o login do mock

---

backend/controllers/login.js
backend/routers/index.js

fix: login OK

---

public/src/scripts/classes/Control-game.js
public/src/scripts/html-content/index.js
public/src/scripts/html-content/maze.js
public/src/scripts/logoutGame.js
public/src/scripts/runMazeIsa.js

- Padronizar as nomenclaturas do projeto para o idioma inglês

refactor: translate variables names to english

---

backend/controllers/login.js
backend/controllers/walk.js
public/src/scripts/classes/Control-game.js
public/src/scripts/classes/Player.js
public/src/scripts/request-control.js
public/src/scripts/runMazeIsa.js

AAAAAAAAAAAAAAAAAAEHHHHHHHHHHHHHHHHHHHHHHHHHHH
MULTIPLAYER FUNCIONANDO

moving player

---

public/src/scripts/classes/Control-game.js

Terminar logo esse jogo (pfv, Deus)

Adicionando requisição no pulinho do sapinho.

---

backend/controllers/connection.js
backend/controllers/disconnection.js
backend/controllers/login.js
backend/controllers/logout.js
backend/controllers/walk.js
backend/routers/routes.js
public/src/scripts/classes/Control-game.js
public/src/scripts/classes/Player.js
public/src/scripts/enter.js
public/src/scripts/exit.js
public/src/scripts/request-control.js
public/src/scripts/runMazeIsa.js

LOGOUT - back e front
Houveram mudanças no método de enviar mensagem no logout;

Logout refactor

---

public/src/scripts/classes/Control-game.js
public/src/scripts/enter.js

Corrigir o login com a tecla enter

fix: Login with enter key, and lock moves when finish maze

---

backend/controllers/login.js
public/index.html
public/index.js
public/src/scripts/enter.js
public/src/scripts/runMazeIsa.js
public/src/styles/style.css

Um simples name board que mostra os usernames de quem entrou no jogo

Simple name board

---

public/src/scripts/html-content/enter-form.js

bug do enter resolvido

---

backend/app.js
package.json
public/src/scripts/classes/Player.js
webpack.config.js

Configuração do webpack e das portas/ip

---

backend/__mock__/data-mock.js
backend/app.js
backend/controllers/connection.js
backend/controllers/end.js
backend/controllers/login.js
backend/controllers/logout.js
public/src/scripts/runMazeIsa.js

Correção de um pequeno bug que ocorria quando executava no localhost, além da remoção de todos os usuários no endgame, pois se você fechasse o jogo sem apartar o botão sair, seu sapinho continuava lá.
Não testado no servidor

Disconnect bug - fixed

---

backend/__mock__/data-mock.js
backend/app.js
backend/controllers/connection.js
backend/controllers/end.js
backend/controllers/login.js
backend/controllers/logout.js
public/src/scripts/runMazeIsa.js

Revert "Disconnect bug - fixed"

---

public/index.html
public/src/scripts/runMazeIsa.js
public/src/styles/style.css

- Apagar o `nameboard` que fica embaixo do formulário de entrada do jogo
1 "buildar" a aplicação
2 inserir um nome válido e entrar no jogo
3 jogar uma partida e clicar em "sair" do modal de fim de jogo
4 validar a ausência do `nameboard` com os nomes dos jogadores embaixo do formulário

fix: delete nameboard from html

---

public/src/scripts/classes/Control-game.js

Add de uma nova função, paredes fantasmas, possuem 25% de chance de aparecer
Pode ter paredes que levam para fora do mapa
Jogando

Created fake wall

---

Procfile

feat: heroku file settings
